# fly.toml app configuration file generated for tuist-newsletter on 2024-06-25T09:30:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tuist-newsletter"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "./listmonk --install --idempotent --yes && ./listmonk --upgrade --yes"

[env]
  LISTMONK_app__address = "0.0.0.0:9000"
  LISTMONK_db__max_idle = "25"
  LISTMONK_db__max_lifetime = "300s"
  LISTMONK_db__max_open = "25"
  LISTMONK_db__port = "5432"
  TZ = "Europe/Berlin"

[[mounts]]
  source = "tuist_newsletter"
  destination = "/listmonk/uploads"

[[services]]
  protocol = "tcp"
  internal_port = 9000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          Referrer-Policy = "strict-origin-when-cross-origin"
          Strict-Transport-Security = "max-age=63072000; includeSubDomains"
          X-Content-Type-Options = "nosniff"
          X-Frame-Options = "SAMEORIGIN"
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/listmonk/public"
  url_prefix = "/public"

[[statics]]
  guest_path = "/listmonk/uploads"
  url_prefix = "/uploads"
